FROM mariadb:latest

ENV MARIDB_ROOT_PASSWORD=${MARIDB_ROOT_PASSWORD}
ENV MARIDB_DATABASE=${MARIDB_DATABASE}
ENV MARIDB_USER=${MARIDB_USER}
ENV MARIDB_PASSWORD=${MARIDB_PASSWORD}

EXPOSE 3306

ENTRYPOINT ["mysqld", "--bind-address=0.0.0.0"]
